### ISSUE TITLE
question marks aren't properly encoded, producing bad URLs

### ISSUE THREAD

**Issue by dholbert** [jgraham/arewewptyet#2]
For WPT tests where the test itself has URL params (`?a=b&c=d`) in the URL, the `wpt.fyi/results` page seems to require the question-mark, ampersand, and equals sign to be url-encoded, since wpt.fyi appends its own URL-params at the end of the URL (`?label=experimental` etc.) which are distinct from the test URL.

We're not handling that properly right now, which means we produce broken wpt.fyi links for such tests.

For example, this CSV file...
https://jgraham.github.io/arewewptyet/interop-2023/interop-2023-webcompat.csv
...has e.g. the following entry:
> "/editing/other/insertparagraph-in-inline-editing-host.tentative.html?white-space=pre&display=table-cell&method=enter",18,0,0,""

...which we end up linking like so in our internal spreadsheet:
https://wpt.fyi/results//editing/other/insertparagraph-in-inline-editing-host.tentative.html?white-space=pre&display=table-cell&method=enter

...and that's a broken link.  The correct link (taken from the wpt.fyi dashboard itself, e.g. from the directory view for this test) is:
https://wpt.fyi/results/editing/other/insertparagraph-in-inline-editing-host.tentative.html%3Fwhite-space%3Dpre%26display%3Dtable-cell%26method%3Denter

...which is almost what we've got, but with url-encoded question-mark / ampersand / equals (and without the duplicate `/` after `results`, though that part doesn't seem to matter).

**Comment by dholbert** [comment]
(I'm not sure whether it's easier to fix this in the CSV file or in the spreadsheet that consumes it, but I figured I'd get it on-file to be addressed one way or another.  CC @jgraham to take a look when he's able; thanks!)

**Comment by jgraham** [comment]
Good catch, thanks.

Putting the entire test id through `encodeurl` in the spreadsheet seems to work, even though we also end up encoding some additional characters (e.g. `/`).
